name = "swyxdotio-podcast-redirects"
account_id = "2d017c943ff16e4c52783635ef05e535"
main = "workers/podcast-redirects/index.js"
compatibility_date = "2026-08-25"
workers_dev = false
preview_urls = false

[[routes]]
pattern = "mixtape.swyx.io"
custom_domain = true
