<style>
  .content {
    padding: 1em;
    max-width: var(--line-length);
    margin: 0 auto;
    overflow: auto;
  }
  .content :global(h2) {
    font-weight: bold;
  }
  .content :global(h3) {
    font-weight: bold;
  }

  /* Add space to the left of the anchor
     generated by `remark-autolink-headings`
     Ref: https://github.com/sw-yx/ssg/blob/c920826e062f379e3634ae8bd26c3b037ec12b40/packages/source-devto/src/index.ts#L27-L38
     */
  .content :global(
    h1 a[aria-hidden="true"],
    h2 a[aria-hidden="true"],
    h3 a[aria-hidden="true"],
    h4 a[aria-hidden="true"],
    h5 a[aria-hidden="true"],
    h6 a[aria-hidden="true"]
  ) {
    margin-left: 1rem;
  }

  .content :global(code) {
    font-size: 90%;
    background-color: rgba(29, 80, 80, 0.3);
    padding: 0.25em 0.5em;
  }
  .content :global(pre) {
    font-size: 90%;
    background-color: #292d3e;
    box-shadow: inset 1px 1px 5px rgba(0, 0, 0, 0.05);
    padding: 1em;
    border-radius: 2px;
    overflow-x: auto;
  }

  .content :global(pre) :global(code) {
    background-color: transparent;
    padding: 0;
  }

  .content :global(blockquote) {
    padding: 0 1em;
    font-style: italic;
    border-left: 0.25em solid var(--brand-color-primary);
  }
  .content :global(a) {
    border-bottom: 2px solid #F26111;
  }
  .content :global(ul) {
    line-height: 1.5;
  }

  .content :global(li) {
    margin: 0 0 0.5em 0;
  }
  .content :global(.icon-link) {
    font-size: smaller;
  }

  .content :global(img) {
    max-width: 80%;
    margin: 0 auto;
    display: block;
  }
  @media (min-width: 480px) {
    .content :global(a)::before {
      content: attr(href);
      position: absolute;
      transform: translate(-10rem, 1.5rem) scale(0);
      background: linear-gradient(45deg, var(--hover-color-primary),var(--hover-color-secondary));
      visibility: visible;
      opacity: 0;
      /*transition: all 0.5s; this is buggy*/
      transition-duration: 0.5s;
      transition-property: opacity, transform;
    }
    .content :global(a):hover::before {
      opacity: 1;
      transform: translateY(1.5rem) scale(1);
    }
  }

  :global(#table-of-contents) {
    width: 50%;
    font-size: 1.5em;
    font-weight: bold;
    margin: 0 0 0em 0.25em;
  }
  :global(#table-of-contents + ul) {
    width: 40%;
    min-width: 200px;
    color: var(--link-color);
    background: var(--bg-color-secondary);
    /* font-size: 0.8em; */
    /* position: sticky; */
    padding: 1em 2em;
    margin: 0 0 0.5em 0.5em;
  }
  :global(#table-of-contents + ul li, #table-of-contents + ul li p) {
    margin: 0;
  }
  :global(section) {
    margin-top: 3rem;
  }
  /* :global(section:nth-child(even)) {
    background-color: white;
  }

  :global(section:nth-child(odd)) {
    background-color: papayawhip;
  } */
</style>

<div class="content">
  <slot />
</div>
