'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
const escaped = {
    '"': '&quot;',
    "'": '&#39;',
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;'
};
function escape(html) {
    return String(html).replace(/["'&<>]/g, match => escaped[match]);
}
function each(items, fn) {
    let str = '';
    for (let i = 0; i < items.length; i += 1) {
        str += fn(items[i], i);
    }
    return str;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}

/* src/routes/article/Article.svelte generated by Svelte v3.25.1 */

const css = {
	code: ".prose ul > li{margin-top:0;margin-bottom:0}",
	map: "{\"version\":3,\"file\":\"Article.svelte\",\"sources\":[\"Article.svelte\"],\"sourcesContent\":[\"<script>\\n  export let data\\n  const { html, frontmatter } = data\\n</script>\\n\\n<style>:global(.prose ul > li) {\\n  margin-top: 0;\\n  margin-bottom: 0;\\n}\\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9yb3V0ZXMvYXJ0aWNsZS9zcmMvcm91dGVzL2FydGljbGUvQXJ0aWNsZS5zdmVsdGUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQ0U7RUFDRSxhQUFhO0VBQ2IsZ0JBQWdCO0FBQ2xCIiwiZmlsZSI6InNyYy9yb3V0ZXMvYXJ0aWNsZS9BcnRpY2xlLnN2ZWx0ZSIsInNvdXJjZXNDb250ZW50IjpbIlxuICA6Z2xvYmFsKC5wcm9zZSB1bCA+IGxpKSB7XG4gICAgbWFyZ2luLXRvcDogMDtcbiAgICBtYXJnaW4tYm90dG9tOiAwO1xuICB9XG4iXX0= */</style>\\n\\n<svelte:head>\\n  <title>{frontmatter.title} | swyx.io</title>\\n</svelte:head>\\n<a href=\\\"/\\\">&LeftArrow; Home</a>\\n\\n<article\\n  class=\\\"px-4 py-10 max-w-3xl mx-auto sm:px-6 sm:py-12 lg:max-w-4xl lg:py-16\\n    lg:px-8 xl:max-w-6xl\\\">\\n    \\n    <div class=\\\"flex gap-2\\\">\\n      {#each frontmatter.categories as tag}\\n      <span\\n        class=\\\"inline-flex items-center px-3 py-0.5 rounded-full text-sm\\n          font-medium leading-5 bg-indigo-100 text-indigo-800\\\">\\n        {tag}\\n      </span>\\n    {/each}\\n    </div>\\n  <div class=\\\"prose lg:prose-xl\\\">\\n    <div class=\\\"title\\\">\\n      <h1 class=\\\"text-white\\\">{frontmatter.title}</h1>\\n      {#if frontmatter.author}<small>By {frontmatter.author}</small>{/if}\\n    </div>\\n\\n    {#if html}\\n      {@html html}\\n    {:else}\\n      <h1>There was a problem rendering this page - please let @swyx know!</h1>\\n    {/if}\\n  </div>\\n</article>\\n\"],\"names\":[],\"mappings\":\"AAKe,cAAc,AAAE,CAAC,AAC9B,UAAU,CAAE,CAAC,CACb,aAAa,CAAE,CAAC,AAClB,CAAC\"}"
};

const Article = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { data } = $$props;
	const { html, frontmatter } = data;
	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
	$$result.css.add(css);

	return `${($$result.head += `${($$result.title = `<title>${escape(frontmatter.title)} | swyx.io</title>`, "")}`, "")}
<a href="${"/"}">← Home</a>

<article class="${"px-4 py-10 max-w-3xl mx-auto sm:px-6 sm:py-12 lg:max-w-4xl lg:py-16\n    lg:px-8 xl:max-w-6xl"}"><div class="${"flex gap-2"}">${each(frontmatter.categories, tag => `<span class="${"inline-flex items-center px-3 py-0.5 rounded-full text-sm\n          font-medium leading-5 bg-indigo-100 text-indigo-800"}">${escape(tag)}
      </span>`)}</div>
  <div class="${"prose lg:prose-xl"}"><div class="${"title"}"><h1 class="${"text-white"}">${escape(frontmatter.title)}</h1>
      ${frontmatter.author
	? `<small>By ${escape(frontmatter.author)}</small>`
	: ``}</div>

    ${html
	? `${html}`
	: `<h1>There was a problem rendering this page - please let @swyx know!</h1>`}</div></article>`;
});

module.exports = Article;
