'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
function get_current_component() {
    if (!current_component)
        throw new Error(`Function called outside component initialization`);
    return current_component;
}
function onMount(fn) {
    get_current_component().$$.on_mount.push(fn);
}
const escaped = {
    '"': '&quot;',
    "'": '&#39;',
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;'
};
function escape(html) {
    return String(html).replace(/["'&<>]/g, match => escaped[match]);
}
function each(items, fn) {
    let str = '';
    for (let i = 0; i < items.length; i += 1) {
        str += fn(items[i], i);
    }
    return str;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}

/* src/components/Clock/Clock.svelte generated by Svelte v3.25.1 */

const css = {
	code: "svg.svelte-vi96gj{width:100%;height:100%}.clock-face.svelte-vi96gj{stroke:#333;fill:white}.minor.svelte-vi96gj{stroke:#999;stroke-width:0.5}.major.svelte-vi96gj{stroke:#333;stroke-width:1}.hour.svelte-vi96gj{stroke:#333}.minute.svelte-vi96gj{stroke:#666}.second.svelte-vi96gj,.second-counterweight.svelte-vi96gj{stroke:rgb(180, 0, 0)}.second-counterweight.svelte-vi96gj{stroke-width:3}",
	map: "{\"version\":3,\"file\":\"Clock.svelte\",\"sources\":[\"Clock.svelte\"],\"sourcesContent\":[\"<script>\\n  import { onMount } from \\\"svelte\\\";\\n\\n  let time = new Date();\\n\\n  // these automatically update when `time`\\n  // changes, because of the `$:` prefix\\n  $: hours = time.getHours();\\n  $: minutes = time.getMinutes();\\n  $: seconds = time.getSeconds();\\n\\n  onMount(() => {\\n    const interval = setInterval(() => {\\n      time = new Date();\\n    }, 1000);\\n\\n    return () => {\\n      clearInterval(interval);\\n    };\\n  });\\n</script>\\n\\n<style>svg {\\n  width: 100%;\\n  height: 100%;\\n}\\n\\n.clock-face {\\n  stroke: #333;\\n  fill: white;\\n}\\n\\n.minor {\\n  stroke: #999;\\n  stroke-width: 0.5;\\n}\\n\\n.major {\\n  stroke: #333;\\n  stroke-width: 1;\\n}\\n\\n.hour {\\n  stroke: #333;\\n}\\n\\n.minute {\\n  stroke: #666;\\n}\\n\\n.second,\\n  .second-counterweight {\\n  stroke: rgb(180, 0, 0);\\n}\\n\\n.second-counterweight {\\n  stroke-width: 3;\\n}\\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9jb21wb25lbnRzL0Nsb2NrL3NyYy9jb21wb25lbnRzL0Nsb2NrL0Nsb2NrLnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFDRTtFQUNFLFdBQVc7RUFDWCxZQUFZO0FBQ2Q7O0FBRUE7RUFDRSxZQUFZO0VBQ1osV0FBVztBQUNiOztBQUVBO0VBQ0UsWUFBWTtFQUNaLGlCQUFpQjtBQUNuQjs7QUFFQTtFQUNFLFlBQVk7RUFDWixlQUFlO0FBQ2pCOztBQUVBO0VBQ0UsWUFBWTtBQUNkOztBQUVBO0VBQ0UsWUFBWTtBQUNkOztBQUVBOztFQUVFLHNCQUFzQjtBQUN4Qjs7QUFFQTtFQUNFLGVBQWU7QUFDakIiLCJmaWxlIjoic3JjL2NvbXBvbmVudHMvQ2xvY2svQ2xvY2suc3ZlbHRlIiwic291cmNlc0NvbnRlbnQiOlsiXG4gIHN2ZyB7XG4gICAgd2lkdGg6IDEwMCU7XG4gICAgaGVpZ2h0OiAxMDAlO1xuICB9XG5cbiAgLmNsb2NrLWZhY2Uge1xuICAgIHN0cm9rZTogIzMzMztcbiAgICBmaWxsOiB3aGl0ZTtcbiAgfVxuXG4gIC5taW5vciB7XG4gICAgc3Ryb2tlOiAjOTk5O1xuICAgIHN0cm9rZS13aWR0aDogMC41O1xuICB9XG5cbiAgLm1ham9yIHtcbiAgICBzdHJva2U6ICMzMzM7XG4gICAgc3Ryb2tlLXdpZHRoOiAxO1xuICB9XG5cbiAgLmhvdXIge1xuICAgIHN0cm9rZTogIzMzMztcbiAgfVxuXG4gIC5taW51dGUge1xuICAgIHN0cm9rZTogIzY2NjtcbiAgfVxuXG4gIC5zZWNvbmQsXG4gIC5zZWNvbmQtY291bnRlcndlaWdodCB7XG4gICAgc3Ryb2tlOiByZ2IoMTgwLCAwLCAwKTtcbiAgfVxuXG4gIC5zZWNvbmQtY291bnRlcndlaWdodCB7XG4gICAgc3Ryb2tlLXdpZHRoOiAzO1xuICB9XG4iXX0= */</style>\\n\\n<svg viewBox=\\\"-50 -50 100 100\\\">\\n  <circle class=\\\"clock-face\\\" r=\\\"48\\\" />\\n\\n  <!-- markers -->\\n  {#each [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55] as minute}\\n    <line class=\\\"major\\\" y1=\\\"35\\\" y2=\\\"45\\\" transform=\\\"rotate({30 * minute})\\\" />\\n\\n    {#each [1, 2, 3, 4] as offset}\\n      <line class=\\\"minor\\\" y1=\\\"42\\\" y2=\\\"45\\\" transform=\\\"rotate({6 * (minute + offset)})\\\" />\\n    {/each}\\n  {/each}\\n\\n  <!-- hour hand -->\\n  <line class=\\\"hour\\\" y1=\\\"2\\\" y2=\\\"-20\\\" transform=\\\"rotate({30 * hours + minutes / 2})\\\" />\\n\\n  <!-- minute hand -->\\n  <line class=\\\"minute\\\" y1=\\\"4\\\" y2=\\\"-30\\\" transform=\\\"rotate({6 * minutes + seconds / 10})\\\" />\\n\\n  <!-- second hand -->\\n  <g transform=\\\"rotate({6 * seconds})\\\">\\n    <line class=\\\"second\\\" y1=\\\"10\\\" y2=\\\"-38\\\" />\\n    <line class=\\\"second-counterweight\\\" y1=\\\"10\\\" y2=\\\"2\\\" />\\n  </g>\\n</svg>\\n\"],\"names\":[],\"mappings\":\"AAsBO,GAAG,cAAC,CAAC,AACV,KAAK,CAAE,IAAI,CACX,MAAM,CAAE,IAAI,AACd,CAAC,AAED,WAAW,cAAC,CAAC,AACX,MAAM,CAAE,IAAI,CACZ,IAAI,CAAE,KAAK,AACb,CAAC,AAED,MAAM,cAAC,CAAC,AACN,MAAM,CAAE,IAAI,CACZ,YAAY,CAAE,GAAG,AACnB,CAAC,AAED,MAAM,cAAC,CAAC,AACN,MAAM,CAAE,IAAI,CACZ,YAAY,CAAE,CAAC,AACjB,CAAC,AAED,KAAK,cAAC,CAAC,AACL,MAAM,CAAE,IAAI,AACd,CAAC,AAED,OAAO,cAAC,CAAC,AACP,MAAM,CAAE,IAAI,AACd,CAAC,AAED,qBAAO,CACL,qBAAqB,cAAC,CAAC,AACvB,MAAM,CAAE,IAAI,GAAG,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,AACxB,CAAC,AAED,qBAAqB,cAAC,CAAC,AACrB,YAAY,CAAE,CAAC,AACjB,CAAC\"}"
};

const Clock = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let time = new Date();

	onMount(() => {
		const interval = setInterval(
			() => {
				time = new Date();
			},
			1000
		);

		return () => {
			clearInterval(interval);
		};
	});

	$$result.css.add(css);
	let hours;
	let minutes;
	let seconds;
	hours = time.getHours();
	minutes = time.getMinutes();
	seconds = time.getSeconds();

	return `<svg viewBox="${"-50 -50 100 100"}" class="${"svelte-vi96gj"}"><circle class="${"clock-face svelte-vi96gj"}" r="${"48"}"></circle>${each([0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55], minute => `<line class="${"major svelte-vi96gj"}" y1="${"35"}" y2="${"45"}" transform="${"rotate(" + escape(30 * minute) + ")"}"></line>

    ${each([1, 2, 3, 4], offset => `<line class="${"minor svelte-vi96gj"}" y1="${"42"}" y2="${"45"}" transform="${"rotate(" + escape(6 * (minute + offset)) + ")"}"></line>`)}`)}<line class="${"hour svelte-vi96gj"}" y1="${"2"}" y2="${"-20"}" transform="${"rotate(" + escape(30 * hours + minutes / 2) + ")"}"></line><line class="${"minute svelte-vi96gj"}" y1="${"4"}" y2="${"-30"}" transform="${"rotate(" + escape(6 * minutes + seconds / 10) + ")"}"></line><g transform="${"rotate(" + escape(6 * seconds) + ")"}"><line class="${"second svelte-vi96gj"}" y1="${"10"}" y2="${"-38"}"></line><line class="${"second-counterweight svelte-vi96gj"}" y1="${"10"}" y2="${"2"}"></line></g></svg>`;
});

module.exports = Clock;
