'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}

/* src/routes/home/Home.svelte generated by Svelte v3.25.1 */

const Home = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `${($$result.head += `${($$result.title = `<title>swyx&#39;s site</title>`, "")}`, "")}

<div class="${"mx-auto max-w-screen-xl"}"><div class="${"lg:grid lg:grid-cols-12 lg:gap-8"}"><div class="${"px-4 sm:px-6 sm:text-center md:max-w-2xl md:mx-auto lg:col-span-6 lg:text-left lg:flex lg:items-center"}"><div><div class="${"text-sm font-semibold uppercase tracking-wide text-gray-500 sm:text-base lg:text-sm xl:text-base"}">Shawn Swyx Wang
        </div>
        <h2 class="${"mt-4 text-4xl tracking-tight leading-10 font-extrabold text-white sm:mt-5 sm:leading-none sm:text-6xl\n            lg:mt-6 lg:text-5xl xl:text-6xl"}">Welcome to <span class="${"text-indigo-400"}">swyx.io</span>!
        </h2>
        <p class="${"mt-3 text-base text-gray-300 sm:mt-5 sm:text-xl lg:text-lg xl:text-xl"}">I <a href="${"http://github.com/sw-yx"}" class="${"underline text-indigo-300"}">code</a>, <a href="${"https://www.swyx.io/speaking/react-hooks"}" class="${"underline text-indigo-300"}">speak</a>, and <a href="${"https://egghead.io/s/26zf5"}" class="${"underline text-indigo-300"}">teach</a>. But above all, I <a href="${"/ideas"}" class="${"underline text-indigo-300"}">write</a>. If we share interests, I&#39;d love to connect with you!
          </p>

        <div class="${"mt-5 sm:max-w-lg sm:mx-auto sm:text-center lg:text-left lg:mx-0"}"><p class="${"text-base font-medium text-gray-300"}">Join 2,000+ developers and get blog updates every other week!
          </p>
          <form action="${"#"}" method="${"POST"}" class="${"mt-3 sm:flex"}"><input aria-label="${"Email"}" class="${"appearance-none block w-full px-3 py-3 border border-gray-300 text-base leading-6 rounded-md\n                placeholder-gray-500 shadow-sm focus:outline-none focus:placeholder-gray-400 focus:shadow-outline-blue\n                focus:border-blue-300 transition duration-150 ease-in-out sm:flex-1"}" placeholder="${"Enter your email"}">
            <button type="${"submit"}" class="${"mt-3 w-full px-6 py-3 border border-transparent text-base leading-6 font-medium rounded-md\n                text-white bg-indigo-600 shadow-sm hover:bg-indigo-400 focus:outline-none focus:border-gray-300\n                focus:shadow-outline-gray active:bg-indigo-400 transition duration-150 ease-in-out sm:mt-0 sm:ml-3\n                sm:flex-shrink-0 sm:inline-flex sm:items-center sm:w-auto"}">Notify me
            </button></form>
          <p class="${"mt-3 text-sm leading-5 text-gray-300"}">Too soon! <a class="${"font-medium text-gray-300 underline"}" href="${"https://tinyletter.com/swyx/archive"}">Show me
              what I&#39;m signing up for!</a></p></div>
        </div></div>
    <div class="${"mt-12 relative sm:max-w-lg sm:mx-auto lg:mt-0 lg:max-w-none lg:mx-0 lg:col-span-6 lg:flex lg:items-center"}"><div class="${"relative mx-auto w-full rounded-lg shadow-lg lg:max-w-md"}"><button type="${"button"}" class="${"relative block w-full rounded-lg overflow-hidden focus:outline-none focus:shadow-outline"}"><img class="${"w-full"}" src="${"https://avatars2.githubusercontent.com/u/6764957?u=97ad815028595b73b06ee4b0510e66bbe391228d&v=4&s=500"}" alt="${"swyx at niseko"}">
          </button></div></div></div></div>`;
});

module.exports = Home;
