'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
const escaped = {
    '"': '&quot;',
    "'": '&#39;',
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;'
};
function escape(html) {
    return String(html).replace(/["'&<>]/g, match => escaped[match]);
}
function each(items, fn) {
    let str = '';
    for (let i = 0; i < items.length; i += 1) {
        str += fn(items[i], i);
    }
    return str;
}
function validate_component(component, name) {
    if (!component || !component.$$render) {
        if (name === 'svelte:component')
            name += ' this={...}';
        throw new Error(`<${name}> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules`);
    }
    return component;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}
function add_attribute(name, value, boolean) {
    if (value == null || (boolean && !value))
        return '';
    return ` ${name}${value === true ? '' : `=${typeof value === 'string' ? JSON.stringify(escape(value)) : `"${value}"`}`}`;
}

/* src/components/HookDetail/HookDetail.svelte generated by Svelte v3.25.1 */

const css = {
	code: ".list.svelte-1crre33.svelte-1crre33{display:block;margin-bottom:0.5rem;font-size:13px}.list.svelte-1crre33 .code.svelte-1crre33{cursor:help}.hook.svelte-1crre33.svelte-1crre33{max-width:100%;text-overflow:wrap;padding:1rem;border:1px solid #ddd;border-collapse:collapse;margin-bottom:1rem;border-radius:1rem;position:relative;background:white}.hook-number.svelte-1crre33.svelte-1crre33{position:absolute;top:0;right:0px;width:2rem;height:1.75rem;border-top-right-radius:1rem;border-bottom-left-radius:1rem;text-align:center;padding-top:3px;background:#ddd;font-size:14px}.overview.svelte-1crre33.svelte-1crre33{margin-right:1rem}@media(min-width: 768px){.hook.svelte-1crre33.svelte-1crre33:nth-child(even){margin-left:0.5rem}.hook.svelte-1crre33.svelte-1crre33:nth-child(odd){margin-right:0.5rem}}.use.svelte-1crre33.svelte-1crre33{font-size:14px}.use ul{padding-left:1rem}.overview.svelte-1crre33.svelte-1crre33{margin-bottom:0.75rem;padding-bottom:0.75rem;border-bottom:1px solid #ddd}",
	map: "{\"version\":3,\"file\":\"HookDetail.svelte\",\"sources\":[\"HookDetail.svelte\"],\"sourcesContent\":[\"<script>\\n  export let hook;\\n  export let i;\\n\\n  let hover = false;\\n\\n  let x, y;\\n\\n  const hookEntityDefinitions = {\\n    allRequests: `This represents all of the valid requests Elder.js is aware of. This is collected during bootstrap and can be modified on the 'allRequests' hook. It is important to note that 'allRequests' will be different at the 'requestStart' hook during a build because the requests are split between different processes during build time using the allRequests object.`,\\n    hookInterface:\\n      'The hook interface is what defines the \\\"contract\\\" for each hook. It includes what properties the hook has access to and which of those properties can be mutated.',\\n    customProps: 'An object that represents any custom props added during the \\\"customizeHook\\\" hook',\\n    errors: 'An array of errors collected during the build process.',\\n    request:\\n      'An object that represents the paramaters required to generate a specific page on a specific route. This object originating from the all() query of a route.js file.',\\n    helpers:\\n      'An object of helpers loaded from `./src/helpers/index.js` in addition to the Elder.js provided helper functions.',\\n    data: 'An object that is passed to Svelte templates as the \\\"data\\\" prop.',\\n    settings: 'An object representing the elder.config.js and other details about the build.',\\n    routes: 'An object that represents all of the routes registered with Elder.js.',\\n    hooks: 'An array of all of the hooks that have been validated by Elder.js.',\\n    query: 'An object that is initially empty but is reserved for plugins and sites to add database or api access to.',\\n    route: 'An object representing the specific route (similar to a route.js file) for a specific request.',\\n    headStack:\\n      'A \\\"stack\\\" of strings to be merged together (a long with cssStack) that are written to the <head> tag. If you are looking to customize the head you\\\\'re probably better looking at the \\\"headString.\\\"',\\n    cssStack:\\n      'A \\\"stack\\\" of strings to be merged together to create the the cssString prop. This is mainly uses to collect the css strings emitted by SSR\\\\'d Svelte files.',\\n    styleTag: 'The full style tag that is going to be written to the head of the page.',\\n    cssString:\\n      'The the css string that is wrapped in the styleTag. Added purely for convience in case users wanted to minify the css.',\\n    headString: 'The complete <head></head> string just before it is written to the head.',\\n    beforeHydrateStack:\\n      'A \\\"stack\\\" of generally JS script tags that are required to be loaded before a Svelte component is hydrated. This is only written to the page when a Svelte component needs to be hydrated.',\\n    hydrateStack: 'A \\\"stack\\\" Svelte components that will be hydrated.',\\n    customJsStack:\\n      'A \\\"stack\\\" of user specific customJs strings that will to be merged together. This is written after the Svelte components.',\\n    footerStack: 'A \\\"stack\\\" of strings to be merged together that will be added to the footer tag.',\\n    htmlString: 'The fully generated html for the page.',\\n    timings: 'An array of collected timings of the system. These are collected using the performance observer.',\\n    req: \\\"The 'req' object from Express or Polka when Elder.js is being used as middleware.\\\",\\n    next: \\\"The 'next' object from Express or Polka when Elder.js is being used as middleware.\\\",\\n  };\\n</script>\\n\\n<style>.list {\\n  display: block;\\n  margin-bottom: 0.5rem;\\n  font-size: 13px;\\n}\\n\\n.list .code {\\n  cursor: help;\\n}\\n\\n.hook {\\n  max-width: 100%;\\n  text-overflow: wrap;\\n  padding: 1rem;\\n  border: 1px solid #ddd;\\n  border-collapse: collapse;\\n  margin-bottom: 1rem;\\n  border-radius: 1rem;\\n  position: relative;\\n  background: white;\\n}\\n\\n.hook-number {\\n  position: absolute;\\n  top: 0;\\n  right: 0px;\\n  width: 2rem;\\n  height: 1.75rem;\\n  border-top-right-radius: 1rem;\\n  border-bottom-left-radius: 1rem;\\n  text-align: center;\\n  padding-top: 3px;\\n  background: #ddd;\\n  font-size: 14px;\\n}\\n\\n.overview {\\n  margin-right: 1rem;\\n}\\n\\n@media (min-width: 768px) {\\n  .hook:nth-child(even) {\\n    margin-left: 0.5rem;\\n  }\\n\\n  .hook:nth-child(odd) {\\n    margin-right: 0.5rem;\\n  }\\n}\\n\\n.use {\\n  font-size: 14px;\\n}\\n\\n:global(.use ul) {\\n  padding-left: 1rem;\\n}\\n\\n.overview {\\n  margin-bottom: 0.75rem;\\n  padding-bottom: 0.75rem;\\n  border-bottom: 1px solid #ddd;\\n}\\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9jb21wb25lbnRzL0hvb2tEZXRhaWwvc3JjL2NvbXBvbmVudHMvSG9va0RldGFpbC9Ib29rRGV0YWlsLnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFDRTtFQUNFLGNBQWM7RUFDZCxxQkFBcUI7RUFDckIsZUFBZTtBQUNqQjs7QUFFQTtFQUNFLFlBQVk7QUFDZDs7QUFFQTtFQUNFLGVBQWU7RUFDZixtQkFBbUI7RUFDbkIsYUFBYTtFQUNiLHNCQUFzQjtFQUN0Qix5QkFBeUI7RUFDekIsbUJBQW1CO0VBQ25CLG1CQUFtQjtFQUNuQixrQkFBa0I7RUFDbEIsaUJBQWlCO0FBQ25COztBQUVBO0VBQ0Usa0JBQWtCO0VBQ2xCLE1BQU07RUFDTixVQUFVO0VBQ1YsV0FBVztFQUNYLGVBQWU7RUFDZiw2QkFBNkI7RUFDN0IsK0JBQStCO0VBQy9CLGtCQUFrQjtFQUNsQixnQkFBZ0I7RUFDaEIsZ0JBQWdCO0VBQ2hCLGVBQWU7QUFDakI7O0FBRUE7RUFDRSxrQkFBa0I7QUFDcEI7O0FBRUE7RUFDRTtJQUNFLG1CQUFtQjtFQUNyQjs7RUFDQTtJQUNFLG9CQUFvQjtFQUN0QjtBQUNGOztBQUVBO0VBQ0UsZUFBZTtBQUNqQjs7QUFDQTtFQUNFLGtCQUFrQjtBQUNwQjs7QUFFQTtFQUNFLHNCQUFzQjtFQUN0Qix1QkFBdUI7RUFDdkIsNkJBQTZCO0FBQy9CIiwiZmlsZSI6InNyYy9jb21wb25lbnRzL0hvb2tEZXRhaWwvSG9va0RldGFpbC5zdmVsdGUiLCJzb3VyY2VzQ29udGVudCI6WyJcbiAgLmxpc3Qge1xuICAgIGRpc3BsYXk6IGJsb2NrO1xuICAgIG1hcmdpbi1ib3R0b206IDAuNXJlbTtcbiAgICBmb250LXNpemU6IDEzcHg7XG4gIH1cblxuICAubGlzdCAuY29kZSB7XG4gICAgY3Vyc29yOiBoZWxwO1xuICB9XG5cbiAgLmhvb2sge1xuICAgIG1heC13aWR0aDogMTAwJTtcbiAgICB0ZXh0LW92ZXJmbG93OiB3cmFwO1xuICAgIHBhZGRpbmc6IDFyZW07XG4gICAgYm9yZGVyOiAxcHggc29saWQgI2RkZDtcbiAgICBib3JkZXItY29sbGFwc2U6IGNvbGxhcHNlO1xuICAgIG1hcmdpbi1ib3R0b206IDFyZW07XG4gICAgYm9yZGVyLXJhZGl1czogMXJlbTtcbiAgICBwb3NpdGlvbjogcmVsYXRpdmU7XG4gICAgYmFja2dyb3VuZDogd2hpdGU7XG4gIH1cblxuICAuaG9vay1udW1iZXIge1xuICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgICB0b3A6IDA7XG4gICAgcmlnaHQ6IDBweDtcbiAgICB3aWR0aDogMnJlbTtcbiAgICBoZWlnaHQ6IDEuNzVyZW07XG4gICAgYm9yZGVyLXRvcC1yaWdodC1yYWRpdXM6IDFyZW07XG4gICAgYm9yZGVyLWJvdHRvbS1sZWZ0LXJhZGl1czogMXJlbTtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgcGFkZGluZy10b3A6IDNweDtcbiAgICBiYWNrZ3JvdW5kOiAjZGRkO1xuICAgIGZvbnQtc2l6ZTogMTRweDtcbiAgfVxuXG4gIC5vdmVydmlldyB7XG4gICAgbWFyZ2luLXJpZ2h0OiAxcmVtO1xuICB9XG5cbiAgQG1lZGlhIChtaW4td2lkdGg6IDc2OHB4KSB7XG4gICAgLmhvb2s6bnRoLWNoaWxkKGV2ZW4pIHtcbiAgICAgIG1hcmdpbi1sZWZ0OiAwLjVyZW07XG4gICAgfVxuICAgIC5ob29rOm50aC1jaGlsZChvZGQpIHtcbiAgICAgIG1hcmdpbi1yaWdodDogMC41cmVtO1xuICAgIH1cbiAgfVxuXG4gIC51c2Uge1xuICAgIGZvbnQtc2l6ZTogMTRweDtcbiAgfVxuICA6Z2xvYmFsKC51c2UgdWwpIHtcbiAgICBwYWRkaW5nLWxlZnQ6IDFyZW07XG4gIH1cblxuICAub3ZlcnZpZXcge1xuICAgIG1hcmdpbi1ib3R0b206IDAuNzVyZW07XG4gICAgcGFkZGluZy1ib3R0b206IDAuNzVyZW07XG4gICAgYm9yZGVyLWJvdHRvbTogMXB4IHNvbGlkICNkZGQ7XG4gIH1cbiJdfQ== */</style>\\n\\n<div class=\\\"hook\\\">\\n\\n  {#if i || i === 0}\\n    <span class=\\\"hook-number\\\">{i + 1}.</span>\\n  {/if}\\n\\n  <div class=\\\"overview\\\">\\n    <span class=\\\"hook-name\\\">\\n\\n      {#if hook.link && hook.link.length > 0}\\n        <a href={hook.link}>{hook.hook}</a>\\n      {:else}{hook.hook}{/if}\\n    </span>\\n    : {hook.context}\\n  </div>\\n  <div class=\\\"use\\\">\\n    {@html hook.use}\\n  </div>\\n\\n  <div class=\\\"list\\\">\\n    <strong>Props</strong>\\n    :\\n    {#each hook.props as prop}\\n      <div class=\\\"code\\\" data-balloon-length=\\\"medium\\\" data-balloon-pos=\\\"up\\\" aria-label={hookEntityDefinitions[prop]}>\\n        {prop}\\n      </div>\\n    {/each}\\n  </div>\\n  <div class=\\\"list\\\">\\n    <strong>Mutable</strong>\\n    :\\n    {#each hook.mutable as mutable}\\n      <div class=\\\"code\\\" data-balloon-length=\\\"medium\\\" data-balloon-pos=\\\"up\\\" aria-label={hookEntityDefinitions[mutable]}>\\n        {mutable}\\n      </div>\\n    {/each}\\n  </div>\\n\\n  {#if hook.advanced}\\n    <div>\\n      <small>This hook is an 'advanced' hook meaning it geared towards advanced users or plugins.</small>\\n    </div>\\n  {/if}\\n\\n  <small>{hook.expiremental ? 'Expiremental' : 'Stable'} &middot; Location: {hook.location}</small>\\n</div>\\n\"],\"names\":[],\"mappings\":\"AA6CO,KAAK,8BAAC,CAAC,AACZ,OAAO,CAAE,KAAK,CACd,aAAa,CAAE,MAAM,CACrB,SAAS,CAAE,IAAI,AACjB,CAAC,AAED,oBAAK,CAAC,KAAK,eAAC,CAAC,AACX,MAAM,CAAE,IAAI,AACd,CAAC,AAED,KAAK,8BAAC,CAAC,AACL,SAAS,CAAE,IAAI,CACf,aAAa,CAAE,IAAI,CACnB,OAAO,CAAE,IAAI,CACb,MAAM,CAAE,GAAG,CAAC,KAAK,CAAC,IAAI,CACtB,eAAe,CAAE,QAAQ,CACzB,aAAa,CAAE,IAAI,CACnB,aAAa,CAAE,IAAI,CACnB,QAAQ,CAAE,QAAQ,CAClB,UAAU,CAAE,KAAK,AACnB,CAAC,AAED,YAAY,8BAAC,CAAC,AACZ,QAAQ,CAAE,QAAQ,CAClB,GAAG,CAAE,CAAC,CACN,KAAK,CAAE,GAAG,CACV,KAAK,CAAE,IAAI,CACX,MAAM,CAAE,OAAO,CACf,uBAAuB,CAAE,IAAI,CAC7B,yBAAyB,CAAE,IAAI,CAC/B,UAAU,CAAE,MAAM,CAClB,WAAW,CAAE,GAAG,CAChB,UAAU,CAAE,IAAI,CAChB,SAAS,CAAE,IAAI,AACjB,CAAC,AAED,SAAS,8BAAC,CAAC,AACT,YAAY,CAAE,IAAI,AACpB,CAAC,AAED,MAAM,AAAC,YAAY,KAAK,CAAC,AAAC,CAAC,AACzB,mCAAK,WAAW,IAAI,CAAC,AAAC,CAAC,AACrB,WAAW,CAAE,MAAM,AACrB,CAAC,AAED,mCAAK,WAAW,GAAG,CAAC,AAAC,CAAC,AACpB,YAAY,CAAE,MAAM,AACtB,CAAC,AACH,CAAC,AAED,IAAI,8BAAC,CAAC,AACJ,SAAS,CAAE,IAAI,AACjB,CAAC,AAEO,OAAO,AAAE,CAAC,AAChB,YAAY,CAAE,IAAI,AACpB,CAAC,AAED,SAAS,8BAAC,CAAC,AACT,aAAa,CAAE,OAAO,CACtB,cAAc,CAAE,OAAO,CACvB,aAAa,CAAE,GAAG,CAAC,KAAK,CAAC,IAAI,AAC/B,CAAC\"}"
};

const HookDetail = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { hook } = $$props;
	let { i } = $$props;

	const hookEntityDefinitions = {
		allRequests: `This represents all of the valid requests Elder.js is aware of. This is collected during bootstrap and can be modified on the 'allRequests' hook. It is important to note that 'allRequests' will be different at the 'requestStart' hook during a build because the requests are split between different processes during build time using the allRequests object.`,
		hookInterface: "The hook interface is what defines the \"contract\" for each hook. It includes what properties the hook has access to and which of those properties can be mutated.",
		customProps: "An object that represents any custom props added during the \"customizeHook\" hook",
		errors: "An array of errors collected during the build process.",
		request: "An object that represents the paramaters required to generate a specific page on a specific route. This object originating from the all() query of a route.js file.",
		helpers: "An object of helpers loaded from `./src/helpers/index.js` in addition to the Elder.js provided helper functions.",
		data: "An object that is passed to Svelte templates as the \"data\" prop.",
		settings: "An object representing the elder.config.js and other details about the build.",
		routes: "An object that represents all of the routes registered with Elder.js.",
		hooks: "An array of all of the hooks that have been validated by Elder.js.",
		query: "An object that is initially empty but is reserved for plugins and sites to add database or api access to.",
		route: "An object representing the specific route (similar to a route.js file) for a specific request.",
		headStack: "A \"stack\" of strings to be merged together (a long with cssStack) that are written to the <head> tag. If you are looking to customize the head you're probably better looking at the \"headString.\"",
		cssStack: "A \"stack\" of strings to be merged together to create the the cssString prop. This is mainly uses to collect the css strings emitted by SSR'd Svelte files.",
		styleTag: "The full style tag that is going to be written to the head of the page.",
		cssString: "The the css string that is wrapped in the styleTag. Added purely for convience in case users wanted to minify the css.",
		headString: "The complete <head></head> string just before it is written to the head.",
		beforeHydrateStack: "A \"stack\" of generally JS script tags that are required to be loaded before a Svelte component is hydrated. This is only written to the page when a Svelte component needs to be hydrated.",
		hydrateStack: "A \"stack\" Svelte components that will be hydrated.",
		customJsStack: "A \"stack\" of user specific customJs strings that will to be merged together. This is written after the Svelte components.",
		footerStack: "A \"stack\" of strings to be merged together that will be added to the footer tag.",
		htmlString: "The fully generated html for the page.",
		timings: "An array of collected timings of the system. These are collected using the performance observer.",
		req: "The 'req' object from Express or Polka when Elder.js is being used as middleware.",
		next: "The 'next' object from Express or Polka when Elder.js is being used as middleware."
	};

	if ($$props.hook === void 0 && $$bindings.hook && hook !== void 0) $$bindings.hook(hook);
	if ($$props.i === void 0 && $$bindings.i && i !== void 0) $$bindings.i(i);
	$$result.css.add(css);

	return `<div class="${"hook svelte-1crre33"}">${i || i === 0
	? `<span class="${"hook-number svelte-1crre33"}">${escape(i + 1)}.</span>`
	: ``}

  <div class="${"overview svelte-1crre33"}"><span class="${"hook-name"}">${hook.link && hook.link.length > 0
	? `<a${add_attribute("href", hook.link, 0)}>${escape(hook.hook)}</a>`
	: `${escape(hook.hook)}`}</span>
    : ${escape(hook.context)}</div>
  <div class="${"use svelte-1crre33"}">${hook.use}</div>

  <div class="${"list svelte-1crre33"}"><strong>Props</strong>
    :
    ${each(hook.props, prop => `<div class="${"code svelte-1crre33"}" data-balloon-length="${"medium"}" data-balloon-pos="${"up"}"${add_attribute("aria-label", hookEntityDefinitions[prop], 0)}>${escape(prop)}
      </div>`)}</div>
  <div class="${"list svelte-1crre33"}"><strong>Mutable</strong>
    :
    ${each(hook.mutable, mutable => `<div class="${"code svelte-1crre33"}" data-balloon-length="${"medium"}" data-balloon-pos="${"up"}"${add_attribute("aria-label", hookEntityDefinitions[mutable], 0)}>${escape(mutable)}
      </div>`)}</div>

  ${hook.advanced
	? `<div><small>This hook is an &#39;advanced&#39; hook meaning it geared towards advanced users or plugins.</small></div>`
	: ``}

  <small>${escape(hook.expiremental ? "Expiremental" : "Stable")} · Location: ${escape(hook.location)}</small></div>`;
});

/* src/components/HookList/HookList.svelte generated by Svelte v3.25.1 */

const css$1 = {
	code: ".hooks.svelte-gh2zh4{display:grid;grid-template-columns:100%}@media(min-width: 768px){.hooks.svelte-gh2zh4{grid-template-columns:50% 50%}}",
	map: "{\"version\":3,\"file\":\"HookList.svelte\",\"sources\":[\"HookList.svelte\"],\"sourcesContent\":[\"<script>\\n  export let hooks;\\n  import HookDetail from \\\"../HookDetail/HookDetail.svelte\\\";\\n</script>\\n\\n<style>.hooks {\\n  display: grid;\\n  grid-template-columns: 100%;\\n}\\n\\n@media (min-width: 768px) {\\n  .hooks {\\n    grid-template-columns: 50% 50%;\\n  }\\n}\\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9jb21wb25lbnRzL0hvb2tMaXN0L3NyYy9jb21wb25lbnRzL0hvb2tMaXN0L0hvb2tMaXN0LnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFDRTtFQUNFLGFBQWE7RUFDYiwyQkFBMkI7QUFDN0I7O0FBRUE7RUFDRTtJQUNFLDhCQUE4QjtFQUNoQztBQUNGIiwiZmlsZSI6InNyYy9jb21wb25lbnRzL0hvb2tMaXN0L0hvb2tMaXN0LnN2ZWx0ZSIsInNvdXJjZXNDb250ZW50IjpbIlxuICAuaG9va3Mge1xuICAgIGRpc3BsYXk6IGdyaWQ7XG4gICAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiAxMDAlO1xuICB9XG5cbiAgQG1lZGlhIChtaW4td2lkdGg6IDc2OHB4KSB7XG4gICAgLmhvb2tzIHtcbiAgICAgIGdyaWQtdGVtcGxhdGUtY29sdW1uczogNTAlIDUwJTtcbiAgICB9XG4gIH1cbiJdfQ== */</style>\\n\\n<div class=\\\"hooks\\\">\\n  {#each hooks as hook, i}\\n    <HookDetail {hook} {i} />\\n  {/each}\\n\\n</div>\\n\"],\"names\":[],\"mappings\":\"AAKO,MAAM,cAAC,CAAC,AACb,OAAO,CAAE,IAAI,CACb,qBAAqB,CAAE,IAAI,AAC7B,CAAC,AAED,MAAM,AAAC,YAAY,KAAK,CAAC,AAAC,CAAC,AACzB,MAAM,cAAC,CAAC,AACN,qBAAqB,CAAE,GAAG,CAAC,GAAG,AAChC,CAAC,AACH,CAAC\"}"
};

const HookList = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { hooks } = $$props;
	if ($$props.hooks === void 0 && $$bindings.hooks && hooks !== void 0) $$bindings.hooks(hooks);
	$$result.css.add(css$1);
	return `<div class="${"hooks svelte-gh2zh4"}">${each(hooks, (hook, i) => `${validate_component(HookDetail, "HookDetail").$$render($$result, { hook, i }, {}, {})}`)}</div>`;
});

module.exports = HookList;
