'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
function validate_component(component, name) {
    if (!component || !component.$$render) {
        if (name === 'svelte:component')
            name += ' this={...}';
        throw new Error(`<${name}> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules`);
    }
    return component;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}

/* src/components/IconList/IconList.svelte generated by Svelte v3.25.1 */

const IconList = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `

<a href="${"https://swyx.io/rss.xml"}" title="${"RSS"}" target="${"_blank"}"><svg class="${"icon h-6 w-6 text-teal-400 hover:text-red-500"}" fill="${"currentColor"}" viewBox="${"-6 -6 34 34"}" stroke-linecap="${"round"}" stroke-linejoin="${"round"}" stroke-width="${"2"}" aria-hidden="${"true"}"><path d="${"M6.503 20.752c0 1.794-1.456 3.248-3.251 3.248-1.796\n    0-3.252-1.454-3.252-3.248 0-1.794 1.456-3.248 3.252-3.248 1.795.001\n    3.251 1.454 3.251 3.248zm-6.503-12.572v4.811c6.05.062 10.96 4.966\n    11.022\n    11.009h4.817c-.062-8.71-7.118-15.758-15.839-15.82zm0-3.368c10.58.046\n    19.152 8.594 19.183\n    19.188h4.817c-.03-13.231-10.755-23.954-24-24v4.812z"}"></path></svg></a>
<a href="${"https://twitter.com/swyx"}" title="${"twitter"}" target="${"_blank"}" rel="${"me"}" class="${"ml-6 text-teal-400 hover:text-red-500"}"><span class="${"sr-only"}">Twitter</span>
  <svg class="${"h-6 w-6"}" fill="${"currentColor"}" viewBox="${"0 0 24 24"}"><path d="${"M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84"}"></path></svg></a>
<a title="${"github source of this site"}" href="${"https://github.com/sw-yx/swyxdotio"}" target="${"_blank"}" rel="${"noopener"}" class="${"ml-6 text-teal-400 hover:text-red-500"}"><span class="${"sr-only"}">GitHub</span>
  <svg class="${"h-6 w-6"}" fill="${"currentColor"}" viewBox="${"0 0 24 24"}"><path fill-rule="${"evenodd"}" d="${"M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"}" clip-rule="${"evenodd"}"></path></svg></a>
<a title="${"search"}" href="${"/ideas"}"><span class="${"sr-only"}">Search This Site</span>
  <svg class="${"icon h-6 w-6 ml-6 text-teal-400 hover:text-red-500"}" fill="${"currentColor"}" viewBox="${"-4 -4 30 30"}" stroke-linecap="${"round"}" stroke-linejoin="${"round"}" stroke-width="${"2"}" aria-hidden="${"true"}"><path d="${"M15.853 16.56c-1.683 1.517-3.911 2.44-6.353 2.44-5.243\n      0-9.5-4.257-9.5-9.5s4.257-9.5 9.5-9.5 9.5 4.257 9.5 9.5c0 2.442-.923\n      4.67-2.44 6.353l7.44 7.44-.707.707-7.44-7.44zm-6.353-15.56c4.691 0\n      8.5 3.809 8.5 8.5s-3.809 8.5-8.5 8.5-8.5-3.809-8.5-8.5 3.809-8.5\n      8.5-8.5z"}"></path></svg></a>`;
});

/* src/components/Home/MobileMenu.svelte generated by Svelte v3.25.1 */

const MobileMenu = create_ssr_component(($$result, $$props, $$bindings, slots) => {

	return `<nav class="${"relative max-w-screen-xl mx-auto flex items-center justify-between px-4 sm:px-6 pt-6 pb-6 sm:pb-12"}"><div class="${"flex items-center flex-1"}"><div class="${"flex items-center justify-between w-full md:w-auto"}"><a href="${"/"}" aria-label="${"Home"}" class="${"text-white"}">swyx.io </a>
      <div class="${"-mr-2 flex items-center md:hidden"}"><button type="${"button"}" class="${"inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:bg-gray-700\n            focus:outline-none focus:bg-gray-700 transition duration-150 ease-in-out"}" id="${"main-menu"}" aria-label="${"Main menu"}" aria-haspopup="${"true"}"><svg class="${"h-6 w-6"}" stroke="${"currentColor"}" fill="${"none"}" viewBox="${"0 0 24 24"}"><path stroke-linecap="${"round"}" stroke-linejoin="${"round"}" stroke-width="${"2"}" d="${"M4 6h16M4 12h16M4 18h16"}"></path></svg></button></div></div>
    <div class="${"hidden space-x-10 md:flex md:ml-10"}"><a href="${"/ideas"}" class="${"font-medium text-teal-400 hover:text-red-500 transition duration-150 ease-in-out"}">Ideas</a>
      </div></div>
  
  ${validate_component(IconList, "IconList").$$render($$result, {}, {}, {})}</nav>

${ ``}`;
});

module.exports = MobileMenu;
