'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
const escaped = {
    '"': '&quot;',
    "'": '&#39;',
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;'
};
function escape(html) {
    return String(html).replace(/["'&<>]/g, match => escaped[match]);
}
function each(items, fn) {
    let str = '';
    for (let i = 0; i < items.length; i += 1) {
        str += fn(items[i], i);
    }
    return str;
}
function validate_component(component, name) {
    if (!component || !component.$$render) {
        if (name === 'svelte:component')
            name += ' this={...}';
        throw new Error(`<${name}> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules`);
    }
    return component;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}
function add_attribute(name, value, boolean) {
    if (value == null || (boolean && !value))
        return '';
    return ` ${name}${value === true ? '' : `=${typeof value === 'string' ? JSON.stringify(escape(value)) : `"${value}"`}`}`;
}

/* src/components/Showcase/ShowcaseItem.svelte generated by Svelte v3.25.1 */

const ShowcaseItem = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { item } = $$props;

	const shorten = str => str
	? str.length > 200 ? str.slice(0, 100) + "..." : str
	: undefined;

	let shortDesc = shorten(item.desc) || shorten(item.description);
	let longDesc = item.description || item.desc || "No description provided. Suggest one!";
	if ($$props.item === void 0 && $$bindings.item && item !== void 0) $$bindings.item(item);

	return `<li class="${[
		"col-span-1 bg-gray-100 rounded-lg shadow flex flex-col justify-between\n    border-4 transition duration-100 transform hover:-translate-y-1",
		(item.type === "Essays" ? "border-green-500" : "") + " " + (item.type === "Talks" ? "border-blue-500" : "") + " " + (item.type === "Podcasts" ? "border-teal-500" : "")
	].join(" ").trim()}"><div><div class="${"w-full flex items-center justify-between p-6 space-x-6"}"><div class="${"flex-1 truncate"}">
        <div class="${""}"><span class="${[
		"flex-shrink-0 inline-block px-2 py-0.5 text-xs leading-4\n              font-medium rounded-full",
		(item.type === "Essays" ? "bg-green-100" : "") + " " + (item.type === "Essays" ? "text-green-800" : "") + " " + (item.type === "Talks" ? "bg-blue-100" : "") + " " + (item.type === "Talks" ? "text-blue-800" : "") + " " + (item.type === "Podcasts" ? "bg-teal-100" : "") + " " + (item.type === "Podcasts" ? "text-teal-800" : "")
	].join(" ").trim()}">
            ${escape(item.type)}</span>
          <h3 class="${"text-gray-900 text-sm leading-5 font-medium whitespace-normal\n              inline"}">${escape(item.title)}</h3></div>
        
        ${ ``}
        <p class="${"mt-1 text-gray-700 text-sm leading-5 whitespace-normal"}">${ shortDesc
	? `<div class="${""}">${escape(shortDesc)}</div>`
	: `<div>${escape(longDesc)}</div>

            <dl>${item.canonical
		? `<div class="${"py-2 sm:grid sm:grid-cols-3 sm:gap-4"}"><dt class="${"text-sm leading-5 font-medium text-gray-500"}">Originally posted at:
                  </dt>
                  <dd class="${"mt-1 text-sm leading-5 text-gray-900 sm:mt-0\n                      sm:col-span-2"}"><a class="${"underline hover:text-blue-700"}"${add_attribute("href", item.canonical, 0)}>${escape(item.canonical)}</a></dd></div>`
		: ``}${item.url
		? `<div class="${"py-2 sm:grid sm:grid-cols-3 sm:gap-4\n                    break-all"}"><dt class="${"text-sm leading-5 font-medium text-gray-500"}">External URL
                  </dt>
                  <dd class="${"mt-1 text-sm leading-5 text-gray-900 sm:mt-0\n                      sm:col-span-2"}"><a class="${"underline hover:text-blue-700"}"${add_attribute("href", item.url, 0)}>${escape(item.url)}</a></dd></div>`
		: ``}${item.slides
		? `<div class="${"py-2 sm:grid sm:grid-cols-3 sm:gap-4"}"><dt class="${"text-sm leading-5 font-medium text-gray-500"}">Slides
                  </dt>
                  <dd class="${"mt-1 text-sm leading-5 text-gray-900 sm:mt-0\n                      sm:col-span-2"}"><a class="${"underline hover:text-blue-700"}"${add_attribute("href", item.slides, 0)}>${escape(item.slides)}</a></dd></div>`
		: ``}${item.categories
		? `<div class="${"py-5 sm:grid sm:grid-cols-3 sm:gap-4"}"><dt class="${"text-sm leading-5 font-medium text-gray-500"}">Categories
                  </dt>
                  <dd class="${"mt-1 text-sm leading-5 text-gray-900 sm:mt-0\n                      sm:col-span-2"}">${escape(item.categories && item.categories.length
			? item.categories.join(", ")
			: "Uncategorized")}</dd></div>`
		: ``}</dl>

            ${item.instances
		? `<ul class="${"border border-gray-200 rounded-md list-disc"}">${each(item.instances, instance => `<li class="${"pr-4 flex items-center justify-between text-sm\n                      leading-5"}"><a class="${"underline hover:text-blue-800"}"${add_attribute("href", instance.video, 0)}>On ${escape(new Date(instance.date).toDateString().slice(4))} at ${escape(instance.venue)}</a>
                    
                    
                    
                  </li>`)}</ul>`
		: ``}

            `}</p></div>
      
      <div></div></div></div>
  <div class="${"border-t border-gray-200"}"><div class="${"-mt-px flex"}"><div class="${"w-0 flex-1 flex border-r border-gray-200"}"><button class="${[
		"relative -mr-px w-0 flex-1 inline-flex items-center\n            justify-center py-4 text-sm leading-5 text-gray-700 font-medium\n            border border-transparent rounded-bl-lg hover:bg-gray-300\n            focus:outline-none focus:shadow-outline-blue focus:border-blue-300\n            focus:z-10 transition ease-in-out duration-150",
		( "") + " " + ( "")
	].join(" ").trim()}">
          <svg class="${"w-5 h-5 text-gray-400"}" viewBox="${"0 0 20 20"}" fill="${"currentColor"}"><path d="${"M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z"}"></path><path d="${"M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z"}"></path></svg>
          <span class="${"ml-3"}">More Info</span></button></div>
      <div class="${"-ml-px w-0 flex-1 flex"}">${item.type === "Essays" && item.slug
	? `<a${add_attribute("href", `/${item.slug}`, 0)} class="${"relative w-0 flex-1 inline-flex items-center justify-center\n              py-4 text-sm leading-5 text-gray-700 font-medium border\n              border-transparent rounded-br-lg hover:text-gray-500\n              focus:outline-none focus:shadow-outline-blue focus:border-blue-300\n              focus:z-10 transition ease-in-out duration-150"}">
            <svg class="${"w-5 h-5 text-gray-400"}" viewBox="${"0 0 20 20"}" fill="${"currentColor"}"><path d="${"M2 3a1 1 0 011-1h2.153a1 1 0 01.986.836l.74 4.435a1 1 0 01-.54 1.06l-1.548.773a11.037 11.037 0 006.105 6.105l.774-1.548a1 1 0 011.059-.54l4.435.74a1 1 0 01.836.986V17a1 1 0 01-1 1h-2C7.82 18 2 12.18 2 5V3z"}"></path></svg>
            <span class="${"ml-3"}">Read</span></a>
          `
	: `${item.type === "Talks" && item.instances && item.instances[0].video
		? `<a${add_attribute("href", item.instances[0].video, 0)} target="${"_blank"}" rel="${"noopener"}" class="${"relative w-0 flex-1 inline-flex items-center justify-center\n              py-4 text-sm leading-5 text-gray-700 font-medium border\n              border-transparent rounded-br-lg hover:text-gray-500\n              focus:outline-none focus:shadow-outline-blue focus:border-blue-300\n              focus:z-10 transition ease-in-out duration-150"}">
            <svg class="${"w-5 h-5 text-gray-400"}" xmlns="${"http://www.w3.org/2000/svg"}" fill="${"none"}" viewBox="${"0 0 24 24"}" stroke="${"currentColor"}"><path stroke-linecap="${"round"}" stroke-linejoin="${"round"}" stroke-width="${"2"}" d="${"M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"}"></path></svg>
            <span class="${"ml-3"}">Watch</span></a>`
		: `${item.type === "Podcasts" && item.url
			? `<a${add_attribute("href", item.url, 0)} target="${"_blank"}" rel="${"noopener"}" class="${"relative w-0 flex-1 inline-flex items-center justify-center\n              py-4 text-sm leading-5 text-gray-700 font-medium border\n              border-transparent rounded-br-lg hover:text-gray-500\n              focus:outline-none focus:shadow-outline-blue focus:border-blue-300\n              focus:z-10 transition ease-in-out duration-150"}">
            <svg class="${"w-5 h-5 text-gray-400"}" xmlns="${"http://www.w3.org/2000/svg"}" fill="${"none"}" viewBox="${"0 0 24 24"}" stroke="${"currentColor"}"><path stroke-linecap="${"round"}" stroke-linejoin="${"round"}" stroke-width="${"2"}" d="${"M15.536 8.464a5 5 0 010 7.072m2.828-9.9a9 9 0 010 12.728M5.586 15H4a1 1 0 01-1-1v-4a1 1 0 011-1h1.586l4.707-4.707C10.923 3.663 12 4.109 12 5v14c0 .891-1.077 1.337-1.707.707L5.586 15z"}"></path></svg>
            <span class="${"ml-3"}">Listen</span></a>`
			: `<div></div>`}`}`}</div></div></div></li>`;
});

/* src/components/Showcase/Showcase.svelte generated by Svelte v3.25.1 */

const Showcase = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { data } = $$props;
	let filterStr = "";
	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
	let filteredData;

	filteredData = data.filter(x => {
		{
			if ( x.type === "Essays") return true;
			if ( x.type === "Talks") return true;
			if ( x.type === "Podcasts") return true;
		}
	}).map(x => {
		if (x.date) x.effectiveDate = new Date(x.date);
		if (x.instances) x.effectiveDate = new Date(x.instances[0].date);
		return x;
	}).sort((a, z) => z.effectiveDate - a.effectiveDate);

	return `<div class="${"relative max-w-lg mx-auto lg:max-w-7xl mb-8"}"><div class="${"text-center"}"><h1 class="${"text-5xl leading-9 tracking-tight font-extrabold text-gray-200\n        sm:text-4xl sm:leading-10"}">Idea Showcase
    </h1>
    <p class="${"mt-3 text-xl leading-7 text-gray-400 sm:mt-4"}">For Free: ${escape(filteredData.length)} Great Ideas. Lightly Used.
    </p></div></div>

<div><div class="${"flex rounded-md mb-4"}">
    <label for="${"search_candidate"}" class="${"sr-only"}">Search</label>
    <div class="${"relative flex-grow focus-within:z-10"}"><div class="${"absolute inset-y-0 left-0 pl-3 flex items-center"}">
        <label for="${"search_candidate"}"><svg class="${"h-5 w-5 text-gray-400"}" viewBox="${"0 0 20 20"}" fill="${"currentColor"}"><path fill-rule="${"evenodd"}" d="${"M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"}" clip-rule="${"evenodd"}"></path></svg></label>
        <input id="${"search_candidate"}" type="${"text"}" class="${"form-input block w-full rounded-md pl-2\n            transition ease-in-out duration-150 sm:hidden"}" placeholder="${"Filter"}"${add_attribute("value", filterStr, 1)}>
        <input id="${"search_candidate"}" type="${"text"}" class="${"hidden form-input w-full rounded-md pl-2\n            transition ease-in-out duration-150 sm:block sm:text-sm sm:leading-5"}" placeholder="${"Filter ideas"}"${add_attribute("value", filterStr, 1)}></div></div>
    
    <span class="${"relative z-0 inline-flex flex-col sm:flex-row shadow-sm rounded-md"}"><div class="${"inline-flex items-center mr-2 text-gray-400"}">Show:</div>
      <button type="${"button"}" class="${[
		"-ml-px sm:ml-0 relative inline-flex items-center px-4 py-2 sm:rounded-l-md border\n          border-gray-300 bg-white text-sm leading-5 font-medium text-gray-700\n          hover:text-gray-500 focus:z-10 focus:outline-none\n          focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-100\n          active:text-gray-700 transition ease-in-out duration-150",
		 "bg-gray-300" 
	].join(" ").trim()}">Essays
      </button>
      <button type="${"button"}" class="${[
		"-ml-px relative inline-flex items-center px-4 py-2 border\n          border-gray-300 bg-white text-sm leading-5 font-medium text-gray-700\n          hover:text-gray-500 focus:z-10 focus:outline-none\n          focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-100\n          active:text-gray-700 transition ease-in-out duration-150",
		 "bg-gray-300" 
	].join(" ").trim()}">Talks
      </button>
      <button type="${"button"}" class="${[
		"-ml-px relative inline-flex items-center px-4 py-2 border\n          border-gray-300 bg-white text-sm leading-5 font-medium text-gray-700\n          hover:text-gray-500 focus:z-10 focus:outline-none\n          focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-100\n          active:text-gray-700 transition ease-in-out duration-150",
		 "bg-gray-300" 
	].join(" ").trim()}">Podcasts
      </button>
      <button type="${"button"}" class="${[
		"-ml-px relative inline-flex items-center px-4 py-2 border\n          border-gray-300 bg-white text-sm leading-5 font-medium text-gray-700\n          hover:text-gray-500 focus:z-10 focus:outline-none\n          focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-100\n          active:text-gray-700 transition ease-in-out duration-150",
		 ""
	].join(" ").trim()}"><strike>Tutorials</strike></button>
      <button type="${"button"}" class="${[
		"-ml-px relative inline-flex items-center px-4 py-2 sm:rounded-r-md\n          border border-gray-300 bg-white text-sm leading-5 font-medium\n          text-gray-700 hover:text-gray-500 focus:z-10 focus:outline-none\n          focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-100\n          active:text-gray-700 transition ease-in-out duration-150",
		 ""
	].join(" ").trim()}"><strike>Notes</strike></button></span>

    
    ${ ``}</div>

  
    <ul class="${"grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3"}">${filteredData.length
	? each(filteredData, item => `${validate_component(ShowcaseItem, "ShowcaseItem").$$render($$result, { item }, {}, {})}`)
	: `<div class="${"p-8"}">No Content Types Selected! Please see menu above and pick from either Essays, Talks, or Podcasts</div>`}</ul>
  </div>
`;
});

module.exports = Showcase;
