'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
const escaped = {
    '"': '&quot;',
    "'": '&#39;',
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;'
};
function escape(html) {
    return String(html).replace(/["'&<>]/g, match => escaped[match]);
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}
function add_attribute(name, value, boolean) {
    if (value == null || (boolean && !value))
        return '';
    return ` ${name}${value === true ? '' : `=${typeof value === 'string' ? JSON.stringify(escape(value)) : `"${value}"`}`}`;
}

/* src/routes/home/test.svelte generated by Svelte v3.25.1 */

const Test = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<div class="${"relative bg-gray-800 overflow-hidden"}"><div class="${"relative pt-6 pb-16 md:pb-20 lg:pb-24 xl:pb-32"}"><div class="${"ejs-component"}" data-ejs-component="${"MobileMenu"}"${add_attribute("data-ejs-props", JSON.stringify({}), 0)}${add_attribute("data-ejs-options", JSON.stringify({ "loading": "lazy" }), 0)}></div>


              

    <main class="${"mt-8 sm:mt-16 md:mt-20 lg:mt-24"}"><div class="${"mx-auto max-w-screen-xl"}"><div class="${"lg:grid lg:grid-cols-12 lg:gap-8"}"><div class="${"px-4 sm:px-6 sm:text-center md:max-w-2xl md:mx-auto lg:col-span-6 lg:text-left lg:flex lg:items-center"}"><div class="${"text-sm font-semibold uppercase tracking-wide text-gray-500 sm:text-base lg:text-sm xl:text-base"}">Shawn Swyx Wang
          </div>
          <h2 class="${"mt-4 text-4xl tracking-tight leading-10 font-extrabold text-white sm:mt-5 sm:leading-none sm:text-6xl lg:mt-6 lg:text-5xl xl:text-6xl"}">Welcome to 
            <span class="${"text-indigo-400"}">swyx.io</span>!
          </h2>
          <p class="${"mt-3 text-base text-gray-300 sm:mt-5 sm:text-xl lg:text-lg xl:text-xl"}">I am passionate about Developer Tools and Developer Communities and currently work as a Senior Developer Advocate at AWS. In my free time I teach React, TypeScript, Storybook and Node.js CLI&#39;s at <a href="${"https://egghead.io/s/26zf5"}">Egghead.io</a>, and help run the <a href="${"https://sveltesociety.dev/"}">Svelte Society</a> community of meetups.
          </p>
          <div class="${"mt-5 sm:max-w-lg sm:mx-auto sm:text-center lg:text-left lg:mx-0"}"><p class="${"text-base font-medium text-gray-900"}">Join 2,000+ developers and get blog updates every other week!
            </p>
            <form action="${"#"}" method="${"POST"}" class="${"mt-3 sm:flex"}"><input aria-label="${"Email"}" class="${"appearance-none block w-full px-3 py-3 border border-gray-300 text-base leading-6 rounded-md placeholder-gray-500 shadow-sm focus:outline-none focus:placeholder-gray-400 focus:shadow-outline-blue focus:border-blue-300 transition duration-150 ease-in-out sm:flex-1"}" placeholder="${"Enter your email"}">
              <button type="${"submit"}" class="${"mt-3 w-full px-6 py-3 border border-transparent text-base leading-6 font-medium rounded-md text-white bg-gray-800 shadow-sm hover:bg-gray-700 focus:outline-none focus:border-gray-900 focus:shadow-outline-gray active:bg-gray-900 transition duration-150 ease-in-out sm:mt-0 sm:ml-3 sm:flex-shrink-0 sm:inline-flex sm:items-center sm:w-auto"}">Notify me
              </button></form>
            <p class="${"mt-3 text-sm leading-5 text-gray-500"}">Too soon! <a class="${"font-medium text-gray-900 underline"}" href="${"https://tinyletter.com/swyx/archive"}">Show me what I&#39;m getting first!</a></p>

          </div></div></div>
        <div class="${"mt-12 relative sm:max-w-lg sm:mx-auto lg:mt-0 lg:max-w-none lg:mx-0 lg:col-span-6 lg:flex lg:items-center"}"><div class="${"relative mx-auto w-full rounded-lg shadow-lg lg:max-w-md"}"><button type="${"button"}" class="${"relative block w-full rounded-lg overflow-hidden focus:outline-none focus:shadow-outline"}"><img class="${"w-full"}" src="${"https://avatars2.githubusercontent.com/u/6764957?u=97ad815028595b73b06ee4b0510e66bbe391228d&v=4&s=500"}" alt="${"swyx at niseko"}">
              </button></div></div></div></main></div></div>`;
});

module.exports = Test;
