import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { renderMarkdown } from '../src/lib/markdown.js';

const root = new URL('../', import.meta.url);
const read = (path) => readFile(new URL(path, root), 'utf8');

test('About separates current work, story, and explicitly dated speaker bios', async () => {
	const [source, content] = await Promise.all([
		read('src/routes/about/+page.svelte'),
		read('src/routes/about/archive.md')
	]);
	const html = await renderMarkdown(content);
	assert.match(source, /<h1>Hey, I’m swyx\.<\/h1>/);
	assert.match(source, /class="reading-prose about-copy"/);
	assert.match(source, /src="\/swyx-ski\.jpeg"/);
	assert.doesNotMatch(source, /site-card/);
	for (const id of ['current-work', 'my-story', 'speaker-bio']) {
		assert.ok(source.includes(`href="#${id}"`));
		assert.ok(source.includes(`id="${id}"`));
	}
	assert.match(html, /January 2025 version/);
	assert.match(html, /Please confirm titles before reusing this bio/);
	assert.match(html, /Earlier bio · February 2024/);
	assert.doesNotMatch(html, /swyxkit\.netlify\.app|Tech behind this site/);
	for (const name of ['Netlify', 'Amazon Web Services', 'Temporal', 'Airbyte', 'Two Sigma']) {
		assert.ok(html.includes(name), `Missing work history: ${name}`);
	}
});

test('the press kit has real thumbnails, labeled originals, and no known broken Summit links', async () => {
	const [source, photos] = await Promise.all([
		read('src/routes/about/+page.svelte'),
		read('src/routes/about/photos.md')
	]);
	assert.equal((source.match(/title: '/g) || []).length, 4);
	assert.match(source, /<h2 id="press-photos">Press photos<\/h2>/);
	assert.match(source, /Open full-size ↗/);
	assert.match(source, /loading="lazy"/);
	const html = await renderMarkdown(photos);
	assert.doesNotMatch(html, />https?:\/\//);
	assert.doesNotMatch(html, /aie-cms-uploads\.s3/);
	for (const name of [
		'transparent background',
		'React Advanced',
		'React Miami',
		'JSConf',
		'Cartoon avatars'
	]) {
		assert.ok(html.includes(name), `Missing photo source: ${name}`);
	}
});

test('World’s Fair photos lead the press kit while older conferences remain under show more', async () => {
	const [source, markdown] = await Promise.all([
		read('src/routes/about/+page.svelte'),
		read('src/routes/about/photos.md')
	]);
	const featured = [...source.matchAll(/src: '(\/about-photos\/worlds-fair-[a-z-]+\.webp)'/g)];
	assert.equal(featured.length, 4);
	assert.equal((source.match(/href: 'https:\/\/images\.pixieset\.com\/123558811\/[a-f0-9]+-xxlarge\.jpg'/g) || []).length, 4);
	assert.match(source, /https:\/\/aiengineer\.pixieset\.com\/worldsfair2026\//);
	assert.doesNotMatch(source, /React Miami|React Advanced|tools\.aieconf\.com/);
	assert.match(source, /aspect-ratio: 3 \/ 2;\s*object-fit: contain/);
	assert.match(source, /width="720"\s*height="480"\s*loading="lazy"\s*decoding="async"/);
	let totalBytes = 0;
	for (const [, path] of featured) {
		const bytes = await readFile(new URL(`static${path}`, root));
		assert.equal(bytes.toString('ascii', 0, 4), 'RIFF');
		assert.equal(bytes.toString('ascii', 8, 12), 'WEBP');
		totalBytes += bytes.length;
	}
	assert.ok(totalBytes < 200_000, 'The featured photos stay lightweight');
	const html = await renderMarkdown(markdown);
	assert.match(html, /<details>\s*<summary>More event photos and avatars<\/summary>/);
	assert.match(html, /<h3 id="earlier-speaking-photos">Earlier speaking photos<\/h3>/);
	for (const name of ['React Miami', 'React Advanced', 'Niseko headshot', 'Thursday Nights in AI']) {
		assert.ok(html.includes(name), `Older photo remains available: ${name}`);
	}
});

test('headshots and the first two cartoon avatars are visible without expanding the archive', async () => {
	const html = await renderMarkdown(await read('src/routes/about/photos.md'));
	const archiveStart = html.indexOf('<details>');
	assert.ok(archiveStart > 0);
	const visible = html.slice(0, archiveStart);
	const archive = html.slice(archiveStart);
	assert.match(visible, /<h3 id="headshots">Headshots &amp; avatars<\/h3>/);
	assert.match(visible, /class="photo-preview-grid portrait-previews"/);
	for (const name of ['headshot-small', 'headshot-niseko', 'headshot-transparent', 'headshot-alternate', 'avatar-one', 'avatar-two']) {
		assert.ok(visible.includes(`/about-photos/${name}.webp`), `${name} must be visible by default`);
		assert.ok(!archive.includes(`/about-photos/${name}.webp`), `${name} must not be duplicated in the archive`);
	}
	assert.equal((visible.match(/class="photo-preview"/g) || []).length, 6);
	assert.equal((archive.match(/class="photo-preview"/g) || []).length, 21);
	for (const name of ['React Miami', 'React Advanced', 'Autogenerated portrait three']) {
		assert.ok(archive.includes(name), `${name} remains in the lower tier`);
		assert.ok(!visible.includes(name));
	}
	assert.doesNotMatch(archive, /<details\s+open/);
});

test('every additional press photo has a small local preview and its original link', async () => {
	const [source, markdown] = await Promise.all([
		read('src/routes/about/+page.svelte'),
		read('src/routes/about/photos.md')
	]);
	const html = await renderMarkdown(markdown);
	const previews = [...html.matchAll(/<a\s+class="photo-preview"\s+href="([^"]+)"[\s\S]*?<\/a>/g)];
	assert.equal(previews.length, 27);
	assert.equal((html.match(/class="photo-preview-grid(?: [^"]*)?"/g) || []).length, 4);
	const paths = new Set();
	let totalBytes = 0;
	for (const [preview, href] of previews) {
		assert.match(href, /^https:\/\//);
		assert.match(preview, /aria-label="Open original: /);
		assert.match(preview, /loading="lazy"/);
		assert.match(preview, /decoding="async"/);
		assert.match(preview, /alt="[^"]+"/);
		assert.match(preview, /<figcaption>/);
		const path = preview.match(/src="(\/about-photos\/[a-z-]+\.webp)"/)?.[1];
		assert.ok(path, 'Each preview uses a local thumbnail');
		paths.add(path);
		const bytes = await readFile(new URL(`static${path}`, root));
		assert.equal(bytes.toString('ascii', 0, 4), 'RIFF');
		assert.equal(bytes.toString('ascii', 8, 12), 'WEBP');
		assert.ok(bytes.length < 100_000, `${path} is too large for a thumbnail`);
		totalBytes += bytes.length;
	}
	assert.equal(paths.size, 27);
	assert.ok(totalBytes < 750_000, 'The complete gallery stays lightweight');
	assert.match(html, /drive\.google\.com\/drive\/folders\//);
	assert.match(html, /twitter\.com\/Thoritie\/status\//);
	assert.doesNotMatch(html, /<img[^>]+src="https?:/);
	assert.match(source, /object-fit: contain/);
	assert.match(source, /\.photo-preview:focus-visible/);
	assert.match(source, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
	assert.equal((source.match(/src: '\/about-photos\//g) || []).length, 4);
});

test('social photos include the six approved picks with exact original posts and preserve older photos', async () => {
	const html = await renderMarkdown(await read('src/routes/about/photos.md'));
	const social = html.split('<h3 id="social-photos">')[1].split('<h3 id="cartoon-avatars">')[0];
	assert.equal((social.match(/class="photo-preview"/g) || []).length, 9);
	for (const [slug, source] of [
		['community-flowers', 'MilksandMatcha/status/1993102854035587370/photo/1'],
		['steve-ruiz', 'steveruizok/status/1552271707804782594/photo/1'],
		['mada-seghete', 'mada299/status/2037720889434030083/photo/1'],
		['michelle-bakels', 'MichelleBakels/status/2046913465822933465/photo/1'],
		['omakase', 'MilksandMatcha/status/2089771790063259743/photo/2'],
		['miami-afterparty', 'MilksandMatcha/status/2048888519293075962/photo/1']
	]) {
		assert.ok(social.includes(`href="https://x.com/${source}"`));
		assert.ok(social.includes(`/about-photos/social-${slug}.webp`));
	}
	assert.equal((social.match(/Original post ↗/g) || []).length, 6);
	assert.doesNotMatch(html, /Madisonkanna|2070243087801332070/);
	for (const name of ['one', 'two', 'three']) {
		assert.ok(social.includes(`/about-photos/social-${name}.webp`));
	}
});

test('the personal coat of arms is featured in social photos without replacing any photo', async () => {
	const html = await renderMarkdown(await read('src/routes/about/photos.md'));
	const social = html.split('<h3 id="social-photos">')[1].split('<h3 id="cartoon-avatars">')[0];
	assert.match(social, /<figure class="personal-crest" id="coat-of-arms">/);
	assert.ok(social.indexOf('personal-crest') < social.indexOf('photo-preview-grid'));
	assert.equal((social.match(/class="photo-preview"/g) || []).length, 9);
	assert.match(social, /alt="Personal coat of arms with Singapore and US flags/);
	assert.match(social, /width="800" height="693" loading="lazy" decoding="async"/);
	assert.match(social, /href="\/about-photos\/swyx-coat-of-arms-original.jpg"/);
	assert.match(social, /href="\/about-photos\/swyx-coat-of-arms.svg" download/);
	const preview = await readFile(new URL('static/about-photos/swyx-coat-of-arms.webp', root));
	assert.equal(preview.toString('ascii', 0, 4), 'RIFF');
	assert.ok(preview.length < 100_000);
	const original = await readFile(new URL('static/about-photos/swyx-coat-of-arms-original.jpg', root));
	assert.equal(original.readUInt16BE(0), 0xffd8);
	const svg = await read('static/about-photos/swyx-coat-of-arms.svg');
	assert.match(svg, /<svg /);
	assert.doesNotMatch(svg, /<script|<foreignObject|\bon\w+=/i);
});

test('Portfolio presents its entries in an accessible, uncollapsed responsive table', async () => {
	const source = await read('src/routes/portfolio/+page.svelte');
	assert.equal((source.match(/<h1>/g) || []).length, 1);
	assert.doesNotMatch(source, /site-card|<details/);
	assert.match(source, /<table role="table" aria-describedby="valuation-note">/);
	assert.match(source, /scope="col">Company \/ person/);
	assert.match(source, /scope="row" class="company-cell"/);
	assert.match(source, /@media \(max-width: 700px\)/);
	const companies = JSON.parse(await read('src/lib/data/portfolio.json'));
	for (const id of ['daytona', 'replay', 'artificial-analysis']) {
		assert.ok(companies.find((company) => company.id === id).note, `Missing personal note: ${id}`);
	}
});

test('Portfolio keeps disclosure and advising boundaries accessible after the companies', async () => {
	const source = await read('src/routes/portfolio/+page.svelte');
	assert.match(source, /href="#disclosure"/);
	assert.match(source, /<h2 id="disclosure">A note on editorial independence<\/h2>/);
	assert.ok(source.indexOf('</table>') < source.indexOf('id="disclosure"'));
	assert.match(source, /Original order/);
	assert.match(source, /do not get guaranteed spots/);
	assert.match(source, /pump my bags/);
	assert.match(source, /no longer taking new advising inquiries/);
	assert.match(source, /AI product feedback and launch guidance/);
});
