<script>
  import WebMentions from '../../components/WebMentions/WebMentions.svelte'
  export let data
  const { html, frontmatter, markdown, podcasts, talks, ...rest } = data
  // console.log({frontmatter, rest})
  $: longDesc =
    frontmatter.description ||
    frontmatter.desc ||
    'No description provided. Suggest one!'

  let seoSubtitle = frontmatter && frontmatter.subtitle
  export let seoTitle = seoSubtitle
    ? `${frontmatter && frontmatter.title}: ${seoSubtitle}`
    : `${frontmatter && frontmatter.title}`
  export let seoDescription = frontmatter
    ? frontmatter.desc || frontmatter.description || seoTitle
    : seoTitle
  let slug = frontmatter.slug
  // $: console.log({html, frontmatter})
  let readTime = Math.floor(html.split(' ').length / 250) // https://blog.medium.com/read-time-and-you-bc2048ab620c
  readTime = readTime < 2 ? readTime + " minutes" : readTime + " minute"
</script>

<style>
  /* Add space to the left of the anchor
     generated by `remark-autolink-headings`
     Ref: https://github.com/sw-yx/ssg/blob/c920826e062f379e3634ae8bd26c3b037ec12b40/packages/source-devto/src/index.ts#L27-L38
     */
  .prose
    :global(h1 a[aria-hidden='true'], h2 a[aria-hidden='true'], h3
      a[aria-hidden='true'], h4 a[aria-hidden='true'], h5
      a[aria-hidden='true'], h6 a[aria-hidden='true']) {
    margin-left: 1rem;
  }
  .prose .articleMain :global(h2::before) {
    content: '## ';
  }
  .prose .articleMain :global(h3::before) {
    content: '### ';
  }
  .prose .articleMain :global(h4::before) {
    content: '#### ';
  }

  /* undo ol bug in tailwind typography */
  /* https://github.com/tailwindlabs/tailwindcss-typography/issues/71 */

  :global(.prose .articleMain ol) {
    list-style: decimal;
  }
  :global(.prose .articleMain ol > li) {
    padding-left: 0;
  }
  :global(.prose .articleMain ol > li::before) {
    content: none;
  }
  /* undo ol bug in tailwind typography */

  /* opt out of blockquote quotes */
  /* .prose :global(blockquote p:first-of-type::before) {
    content: none;
  } */
  .prose :global(blockquote) {
    position: relative;
    margin-left: 0;
    padding-left: 1em;
    padding-right: 0.5em;
    font-size: 0.9em;
    line-height: 1.4em;
    margin-right: 0;
    /* font-style: italic; */
  }
  .prose :global(blockquote:before) {
    content: '';
    width: 100%;
    height: 100%;
    position: absolute;
    left: 0;
    pointer-events: none;
  }
  /* .prose :global(a) {
    border-bottom: 2px solid #F26111;
  } */
  .prose :global(.icon-link) {
    font-size: smaller;
  }

  :global(.prose .highlightOnHover) {
    text-decoration: none;
  }
  :global(.prose .highlightOnHover:hover) {
    text-decoration: underline;
  }

  /* this is for the hover link thing */
  /* dont use transition: all 0.5s; this is buggy */
  /* @media (min-width: 480px) {
    .prose :global(a)::before {
      content: attr(href);
      position: absolute;
      transform: translate(-10rem, 1.5rem) scale(0);
      background: linear-gradient(45deg, var(--hover-color-primary),var(--hover-color-secondary));
      visibility: visible;
      opacity: 0;
      transition-duration: 0.5s;
      transition-property: opacity, transform;
    }
    .prose :global(a):hover::before {
      opacity: 1;
      transform: translateY(1.5rem) scale(1);
    }
  } */
</style>

<svelte:head>
  <title>{frontmatter.title} | swyx.io</title>
  <meta property="og:url" content={`https://www.swyx.io/${slug}`} />
  <meta property="og:type" content="article" />
  <meta property="og:title" content={seoTitle} />
  <meta name="Description" content={seoDescription} />
  <meta property="og:description" content={seoDescription} />
  <meta
    property="og:image"
    content="https://www.swyx.io/og_image/writing.png" />
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:domain" value="swyx.io" />
  <meta name="twitter:creator" value="https://twitter.com/swyx/" />
  <meta name="twitter:title" value={seoTitle} />
  <meta name="twitter:description" value={seoDescription} />
  <meta
    name="twitter:image"
    content="https://www.swyx.io/og_image/writing.png" />
  <meta name="twitter:label1" value="Published on" />
  <meta
    name="twitter:data1"
    value={new Date(frontmatter.date).toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    })} />
  <meta name="twitter:label2" value="Read Time" />
  <meta name="twitter:data2" value={readTime} />
</svelte:head>

<article
  class="px-4 py-10 max-w-3xl mx-auto sm:px-6 sm:py-12 lg:max-w-4xl lg:py-16
    lg:px-8 xl:max-w-6xl">
  <div class="prose lg:prose-xl">
    <div class="title">
      <h1>{frontmatter.title}</h1>
      {#if frontmatter.subtitle}
        <h2 class="mytext-light">{frontmatter.subtitle}</h2>
      {/if}
      {#if longDesc}
        <p class="mytext-light">
          {longDesc}
          {#each frontmatter.categories as tag}
            <span
              class="text-sm italic font-light leading-5">
              #{tag}
            </span>
          {/each}
        </p>
      {/if}
      {#if frontmatter.author}<small>By {frontmatter.author}</small>{/if}
    </div>

    <blockquote class="text-sm font-mono">
      <div>Read time: {readTime}</div>
      {#if frontmatter.date}
        Last updated:
        <time
          datetime={new Date(frontmatter.date)
            .toDateString()
            .slice(
              0,
              10
            )}>{new Date(frontmatter.date).toDateString().slice(4)}</time>
      {/if}
    </blockquote>

    {#if html}
      <div class="articleMain">
        {@html html}
      </div>
    {:else}
      <h1>There was a problem rendering this page - please let @swyx know!</h1>
    {/if}
  </div>

  <div class="flex justify-between">
    <a
      class="dark:text-indigo-400 text-indigo-600 underline hover:dark:text-indigo-200 hover:text-indigo-600"
      href="/ideas?show=Essays">&LeftArrow; More Essays</a>
    <a
      class="text-pink-400 underline hover:text-pink-200 font-bold"
      href="https://tinyletter.com/swyx">❤️ Subscribe via Email ❤️</a>
    <a
      class="dark:text-indigo-400 text-indigo-600 underline hover:dark:text-indigo-200 hover:text-indigo-800"
      href="/about">Featured Essays and Talks &RightArrow;</a>
  </div>
  <WebMentions
    hydrate-client={{ devto_reactions: frontmatter.devto_reactions, targets: [`https://www.swyx.io/${frontmatter.slug}`, frontmatter.devto_url, frontmatter.canonical_url] }} />
</article>
